/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";

const rootRoute = rootRouteImport._addFileChildren(rootRouteImport.children);

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRoute,
} as any);

export interface FileRoutesByPath {
  "/": {
    id: "/";
    path: "/";
    fullPath: "/";
    preLoaderRoute: typeof IndexRoute;
    parentRoute: typeof rootRoute;
  };
}

const rootRouteChildren = {
  IndexRoute: IndexRoute,
};

export const routeTree = rootRoute._addFileChildren(rootRouteChildren);
